"""_common.py - shared utilities for the cbre-property-longlist skill.

Portable path resolution (works on Windows under Claude Code and on Linux
sandboxes), template/version loading, canonical-dataset loading, and optional
JSON-Schema validation. No third-party imports are required at import time;
jsonschema is used only if present.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import normalize as _N  # noqa: E402  (helpers/ is on path by the line above)

# Skill root = the directory that contains helpers/ assets/ templates/ ...
SKILL_ROOT = Path(__file__).resolve().parent.parent

ASSETS = SKILL_ROOT / "assets"
TEMPLATES = SKILL_ROOT / "templates"
TEMPLATE_HTML = ASSETS / "dashboard_template.html"
VERSION_FILE = ASSETS / "VERSION"
SCHEMA_FILE = TEMPLATES / "canonical.schema.json"

DATA_MARKERS = {
    "PROPS": "/* @@INJECT:PROPS@@ */",
    "POIS": "/* @@INJECT:POIS@@ */",
    "REGIONS": "/* @@INJECT:REGIONS@@ */",
}

# every {{token}} the template expects build_dashboard.py to fill
CONFIG_TOKENS = [
    "topbar_meta", "eyebrow", "title_html", "lede", "footer_copyright",
    "kpi_properties", "kpi_countries", "kpi_regions", "kpi_developers",
    "kpi_wh_area", "kpi_rent", "kpi_countries_sub", "kpi_regions_sub",
    "kpi_wh_area_sub", "kpi_rent_sub", "dist_mode",
]


def load_text(path: Path) -> str:
    return Path(path).read_text(encoding="utf-8")


_TEMPLATE_CACHE: str | None = None


def load_template() -> str:
    # Module-level singleton: the 728 KB template is read by build_dashboard.render
    # AND gate_runner validate-html (which also hashes it), several times per run.
    # The file is immutable within a run (make_template.py is a separate maintenance
    # invocation), so cache the parse. Identical bytes every call -> determinism and
    # the byte-stable-chrome guarantee are unaffected.
    global _TEMPLATE_CACHE
    if _TEMPLATE_CACHE is None:
        if not TEMPLATE_HTML.exists():
            raise FileNotFoundError(
                f"template missing: {TEMPLATE_HTML}\n"
                "Run helpers/make_template.py against a reference dashboard first."
            )
        _TEMPLATE_CACHE = load_text(TEMPLATE_HTML)
    return _TEMPLATE_CACHE


def load_version() -> dict:
    """Returns {'label': str, 'chrome_sha256': str}."""
    out = {"label": "", "chrome_sha256": ""}
    if not VERSION_FILE.exists():
        return out
    for i, line in enumerate(load_text(VERSION_FILE).splitlines()):
        line = line.strip()
        if i == 0 and "=" not in line:
            out["label"] = line
        elif line.startswith("chrome_sha256="):
            out["chrome_sha256"] = line.split("=", 1)[1].strip()
    return out


def load_json(path: Path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def load_canonical(path: Path) -> dict:
    return load_json(path)


def emit_review_view(canonical_path) -> None:
    """Write a photo-stripped twin of canonical.json (canonical_review.json, beside
    it) for the JUDGEMENT reviewers (G-honesty / G-trace / G-enrich): the base64
    heroes are ~99% of the multi-MB file and burn the reviewer's context for no
    benefit (they review DATA, not pixels - the contact sheet is the image aid), so
    each data: URI is replaced with a short marker. canonical.json stays
    authoritative; this is a read aid only (gates.md points the data reviewers here).

    It is regenerated by EVERY freeze - run.py's auto-freeze AND a standalone
    `gate_runner.py freeze` - so a re-review after an out-of-band data fix can never
    read a stale twin (the duplicate-review-round bug). Never raises: the review aid
    must never block a freeze."""
    try:
        p = Path(canonical_path)
        d = json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return

    def _strip(v):
        return (f"<image stripped: {len(v)} chars - see canonical.json>"
                if isinstance(v, str) and v.startswith("data:") else v)

    for prop in d.get("properties", []):
        for k in ("photo", "plan"):
            if prop.get(k):
                prop[k] = _strip(prop[k])
        for k in ("images", "gallery"):
            if isinstance(prop.get(k), list):
                prop[k] = [_strip(x) for x in prop[k]]
    try:
        (p.parent / "canonical_review.json").write_text(
            json.dumps(d, ensure_ascii=False, indent=2), encoding="utf-8")
    except Exception:
        pass


def _structural_errors(data: dict) -> list[str]:
    """Dependency-free structural check, used when jsonschema is missing or too
    old to build a validator. Mirrors the schema's required keys so the degraded
    verdict matches the real one instead of the pipeline crashing."""
    errors: list[str] = []
    for key in ("meta", "properties", "pois", "regions"):
        if key not in data:
            errors.append(f"missing top-level key: {key}")
    props = data.get("properties")
    if isinstance(props, list):
        for p in props:
            for req in ("id", "country", "park", "developer", "city", "status", "photo"):
                if req not in p:
                    errors.append(f"property id={p.get('id', '?')} missing required field: {req}")
    return errors


def _best_validator():
    """(ValidatorClass, jsonschema_module) for the newest draft this jsonschema
    build supports, or (None, module) if none is usable / (None, None) if the
    library is absent. The Draft20xx classes only exist on jsonschema >= 4; older
    builds (e.g. the 3.2.0 shipped in some sandboxes) only have Draft7/Draft4."""
    try:
        import jsonschema  # type: ignore
    except Exception:
        return None, None
    for name in ("Draft202012Validator", "Draft201909Validator",
                 "Draft7Validator", "Draft4Validator"):
        v = getattr(jsonschema, name, None)
        if v is not None:
            return v, jsonschema
    return None, jsonschema


def validate_canonical(data: dict) -> list[str]:
    """Return a list of human-readable schema errors ([] == valid).

    Version-tolerant: builds the newest Draft validator the installed jsonschema
    supports. On pre-4.x builds whose resolver doubles the schema's $id base URI
    (raising RefResolutionError even though the schema has no external $refs), it
    validates a copy with $id/$schema stripped. If jsonschema is absent, too old,
    or anything in validator construction/iteration fails, it degrades to a
    minimal structural check rather than crashing the gate (the failure mode that
    hard-stopped real runs on jsonschema 3.2.0)."""
    Validator, js = _best_validator()
    if Validator is None:
        return _structural_errors(data)
    try:
        schema = load_json(SCHEMA_FILE)
        # query the version without touching jsonschema.__version__ (deprecated on
        # 4.x, absent on some builds); importlib.metadata works back to 3.2.0.
        raw = ""
        try:
            from importlib.metadata import version as _pkg_version
            raw = _pkg_version("jsonschema")
        except Exception:
            raw = str(getattr(js, "__version__", "") or "")
        ver = tuple(int(x) for x in raw.split(".")[:2] if x.isdigit())
        if not ver or ver < (4, 0):
            # self-contained schema: drop identity keys so the legacy RefResolver
            # cannot build a doubled base URI and raise RefResolutionError.
            schema = {k: v for k, v in schema.items() if k not in ("$id", "$schema")}
        validator = Validator(schema)
        errors: list[str] = []
        for err in sorted(validator.iter_errors(data), key=lambda e: list(e.path)):
            loc = "/".join(str(x) for x in err.path) or "(root)"
            errors.append(f"{loc}: {err.message}")
        return errors
    except Exception:
        return _structural_errors(data)


def find_leftover_tokens(text: str) -> list[str]:
    return sorted(set(re.findall(r"\{\{[a-zA-Z0-9_]+\}\}", text)))


# Every string field the dashboard render JS reads (some via .replace etc.), so a
# missing key crashes the render. The canonical rule is "never drop a key the chrome
# reads - emit the sentinel". Used by BOTH merge.canonicalize() and build_dashboard
# (the latter as a self-protecting defence for any hand-authored canonical).
STRING_FIELDS = [
    "permitting", "earlyAccess", "leaseTerm", "rentFree", "incentives",
    "divisibleFrom", "officeArea", "expansionBuilding", "expansionPark",
    "clearHeight", "floorLoad", "sprinklers", "loadingDocks", "overheadDoors",
    "electricity", "truckParking", "carParking", "warehouseRent", "officeRent",
    "serviceCharge", "breeam", "motorway", "region", "status", "description",
    # landlord is OPTIONAL (a DISTINCT party from developer, not schema-required): an
    # unknown landlord is the honest 'tbd' sentinel, and FIELD_PRESENT hides the modal
    # /compare landlord row dataset-wide when no input ever carried one.
    "landlord",
]


# schema-REQUIRED property fields (canonical.schema.json $defs.property.required,
# minus id/photo which merge always sets). Filled with an honest sentinel when
# unknown so a property missing one degrades to 'tbd'/'??' instead of HARD-failing
# validate-data with "'<field>' is a required property". Coverage still counts
# these as unfilled (it tests for non-'tbd'), so a thin record is still surfaced -
# the sentinel only prevents the schema crash, it never masks a gap.
REQUIRED_TEXT_SENTINELS = {"developer": "tbd", "city": "tbd", "park": "tbd",
                           "status": "tbd", "country": "??"}

# chrome fields the schema types as string; an honest numeric value from ANY
# extractor (e.g. loadingDocks: 12 from a tracker/vision record) is coerced to a
# clean string so it satisfies the schema instead of hard-failing validate-data.
_COERCE_STR = set(STRING_FIELDS) | set(REQUIRED_TEXT_SENTINELS) | {"landPrice", "mapLink", "reit"}


def _as_text(v):
    """Format a numeric value as a clean string for a string-typed chrome field
    ('12', '11.5'); pass anything else through unchanged."""
    if isinstance(v, bool):
        return str(v)
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return f"{v:g}"
    return v


def core_fill(rec: dict) -> float:
    """Fraction of a candidate record's CORE fields present: city, developer,
    size (warehouse OR plot), price (rent OR land price), status. Shared by the
    run.py vision-routing probe and merge's file-quality demotion so the two
    can never drift apart."""
    def filled(v):
        return not _N.looks_unknown(v)
    has_size = filled(rec.get("warehouseArea")) or filled(rec.get("plotArea"))
    has_price = (filled(rec.get("warehouseRent")) or filled(rec.get("warehouseRentVal"))
                 or filled(rec.get("landPrice")))
    core = [filled(rec.get("city")), filled(rec.get("developer")), has_size,
            has_price, filled(rec.get("status"))]
    return sum(1 for c in core if c) / len(core)


def record_is_poor(rec: dict) -> bool:
    """A record whose deterministic parse looks unreliable: too few core fields,
    a synthesised 'option N' name with no real city, or an implausible rent (a
    misparse like €1 or €216000/m²/yr). Structural/numeric only - no language
    or region tokens."""
    if core_fill(rec) < 0.4:
        return True
    if " option " in str(rec.get("park", "")).lower() and _N.looks_unknown(rec.get("city")):
        return True
    rv = rec.get("warehouseRentVal")
    if isinstance(rv, (int, float)):
        lo, hi = _N.rent_unit_band(rec.get("rentUnit"))
        if not (lo <= rv <= hi):
            return True
    return False


def fill_render_sentinels(p: dict) -> dict:
    """Fill every chrome-read key with its sentinel (honest unknown, never invented)."""
    for f in STRING_FIELDS:
        if _N.looks_unknown(p.get(f)):
            p[f] = "tbd"
    for f, sentinel in REQUIRED_TEXT_SENTINELS.items():
        if _N.looks_unknown(p.get(f)):
            p[f] = sentinel
    if _N.looks_unknown(p.get("landPrice")):
        p["landPrice"] = "—"
    if "reit" not in p:
        p["reit"] = None
    if _N.looks_unknown(p.get("mapLink")):
        p["mapLink"] = ""
    if "warehouseRentVal" not in p:
        p["warehouseRentVal"] = None
    # coerce honest numerics in string-typed fields (loadingDocks: 12 -> "12") so a
    # well-meant integer can't hard-fail the schema; number-typed fields are untouched
    for f in _COERCE_STR:
        v = p.get(f)
        if isinstance(v, (int, float)) and not isinstance(v, bool):
            p[f] = _as_text(v)
    return p
